### ISSUE TITLE
vue-hot-reload

### ISSUE THREAD

**Issue by davidm-public** [alexjoverm/Egghead-Typescript-Vuejs-apps#1]
Hi, enjoyed your talk, thank you.
Just wondering if you've thought about adding a lesson on vue-hot-reload api?
Do you recommend vue-hot-reload-api??

**Comment by alexjoverm** [comment]
Hi @davidm-public,

The project uses vue-loader, which under the hood uses vue-hot-reload-api, as explained in [the doc](https://github.com/vuejs/vue-hot-reload-api)
