### ISSUE TITLE
Simple way to do Two-Way Data Binding

### ISSUE THREAD

**Issue by RehanSaeed** [alexjoverm/Egghead-Typescript-Vuejs-apps#2]
I'd like to do two-way data binding from a child component to a parent one. I think I can use the `sync` binding modifier to achieve this. Lessn 6 shows how to use `@Model` but what about using it with `sync`? Here is a simple idea of what I'm trying to do:

## Parent Component

```
<template>
<progress :is-loaded.sync="isLoaded"/>
</template>

@Component
export default class ParentComponent extends Vue {
  get isLoaded() { return Store.getters["isLoaded"]; }
  set isLoaded(value: boolean) { Store.commit("isLoaded", value); }
}
```

## Child Component

```
<template>
 <progress :value="_value" min="0" max="100"></progress>
  {{_isLoaded}}
</template>

@Component
export default class ChildComponent extends Vue {
  @Prop()
  public isLoaded: boolean;

  public _isLoaded: boolean = this.isLoaded;
  public _value: number;

  @Watch("isLoaded")
  public onIsLoadedChanged() {
    if (!isLoaded) {
      // Animate _value from 0 to 100.
      this._isLoaded = true;
      this.$emit("update:isLoaded", this._isLoaded);
    }
  }
}
```

Do I really have to use two fields `isLoaded` and `_isLoaded` as well as use `this.$emit` with a magic string of `update:isLoaded`? All of this syntax seems very verbose, is there a simpler way? Also, why do I need `@Model` in this case?

**Comment by alexjoverm** [comment]
As stated in the [vue docs](https://vuejs.org/v2/guide/components.html#sync-Modifier) you could use the `.sync` modifier without any problem. Under the hood is compiled to the same thing.
